#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'

require 'kubernetes-deploy'
require 'kubernetes-deploy/restart_task'

raw_deployments = nil
timeout = nil
ARGV.options do |opts|
  opts.on("--deployments=LIST") { |v| raw_deployments = v.split(",") }
  opts.on("--timeout=seconds") { |t| timeout = t.to_i }
  opts.parse!
end

namespace = ARGV[0]
context = ARGV[1]
logger = KubernetesDeploy::FormattedLogger.build(namespace, context)

restart = KubernetesDeploy::RestartTask.new(namespace: namespace, context: context, logger: logger, timeout: timeout)
success = restart.perform(raw_deployments)
exit 1 unless success
